[simulation]
run_mechanical_interactions = true

[visualization]
export = true
live = false
export_interval = 1

    [[visualize_sim_object]]
    name = "MyNeurite"

    [[visualize_sim_object]]
    name = "MyCell"
